Add content tree indicator
trimble-oss/modus-react-bootstrap pull request #85
Opened 2022-07-04 11:35 UTC by msankaran0712

## Description

Add indicator to Tree Item when expanded.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

Manual testing

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (including CHANGELOG updates)
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-07-04 11:46 UTC, coliff commented
I know you said to not focus on sample-workspace - but should that be included at all in this PR? Wouldn't it be better to exclude it until its ready?

2022-07-05 01:05 UTC, msankaran0712 commented on README.md
>  ```html
@coliff Please review

2022-07-05 01:07 UTC, msankaran0712 commented on src/TreeViewItem.tsx
> +              aria-hidden={!finalDragIcon}
@coliff Now this is hidden from accessibility when the drag icon isn't present.

2022-07-05 01:08 UTC, msankaran0712 reviewed
@coliff fixed the below comments,

On the 'Tree with indicator for expand' demo there us an invisible 'Drag the item' div.

This should be removed from this example It would cause accessibility issues.
Can we also replace the inline style display: inline-flex; with class d-inline-flex.
There's an empty item-indent class. Can that be removed? Instead use utility class pl-0 ?

2022-07-05 01:41 UTC, coliff requested changes
this looks great. just 1 tiny last change, I think you should include `<meta name="viewport" content="width=device-width, initial-scale=1" />` meta tag in head - you can run into layout/responsive issues with it removed.

2022-07-05 08:45 UTC, coliff approved these changes

2022-07-06 12:03 UTC, msankaran0712 commented
Need a new PR for the latest feedback comments

2022-07-06 12:03 UTC, closed without merging